__author__ = 'Pranavi'

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

'''


def problem_2():
    sum_so_far = 0
    sequence_val = 0
    fib_prev = 1
    fib_holder = 0
    fib_current = 2
    STOP = 4000000

    while sequence_val < STOP:

        if fib_current % 2 == 0:
            sum_so_far += fib_current

        fib_holder = fib_prev + fib_current
        fib_prev = fib_current
        fib_current = fib_holder

        sequence_val = fib_current

    print("The sum of all even Fibbonaci numbers under 4,000,000 is " + str(sum_so_far) + ".")

problem_2()
